# iSG Guardian Configuration File
# Copy this file to config.yaml and modify as needed

# iSG应用配置
app:
  package_name: "com.linknlink.app.device.isg"
  activity_name: "com.linknlink.app.device.isg.MainActivity"

# 监控配置
monitor:
  check_interval: 30        # 检查间隔(秒)
  restart_delay: 5          # 重启延迟(秒)
  max_restarts: 3           # 最大重启次数
  cooldown_time: 300        # 冷却时间(秒)

# 日志配置
logging:
  crash_log_dir: "data/crash_logs"
  status_log_file: "data/app_status.log"
  max_log_files: 50         # 最大日志文件数
  max_file_size: "5MB"      # 单文件最大大小
  retention_days: 7         # 保留天数

# MQTT配置 (可选)
mqtt:
  enabled: true
  broker: "192.168.3.60"
  port: 1883
  username: "admin"              # 如果需要认证
  password: "admin"              # 如果需要认证
  topic_prefix: "isg"
  device_id: "isg_guardian"